services:
  mysqldb:
    image: mysql:latest
    expose: # do not open port(s) on HOST
      - "3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 15s
      timeout: 15s
      retries: 15
    networks:
      - app_internal

  migrate:
    build:
      context: .
      dockerfile: ./migrate/Dockerfile
    restart: "no"
    environment:
      DB_HOST: mysqldb
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DBA_PASS: ${DB_ROOT_PASSWORD}
      ADM_USER: ${DEFAULT_ADM}
      ADM_EMAIL: ${DEFAULT_ADM_EMAIL}
      ADM_PASS: ${DEFAULT_ADM_PASS}
    networks:
      - app_internal
    depends_on:
      mysqldb:
        condition: service_healthy

  app:
    restart: unless-stopped
    environment:
      PROD: ${PROD}
      ORIGIN: ${ORIGIN}
      SALT: ${SALT}
      DB_HOST: mysqldb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      COOKIE_LIFETIME: ${COOKIE_LIFETIME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - uploads:${UPLOADS_DIR}
    depends_on:
      mysqldb:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - app_internal

volumes:
  db_data:
  uploads:

networks:
  app_internal: