services:
  db:
    image: mysql:latest
    container_name: meme68_db
    expose: # do not open port(s) on HOST
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_internal

  certbot:
    image: certbot/certbot
    container_name: meme68_certbot
    restart: unless-stopped
    volumes:
      - certs:/etc/letsencrypt
      - ../webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"

  app:
    container_name: meme68_web
    ports: # open port(s) on HOST
      - "80:80"
      - "443:443"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - uploads:/var/www/project/uploads
      - certs:/etc/letsencrypt # allow nginx to view the SSL certs
      - ../webroot:/var/www/certbot # allow for certbot challenge
    depends_on:
      db:
        condition: service_healthy
      certbot:
        condition: service_started
    networks:
      - app_internal

volumes:
  db_data:
  certs:
  uploads:

networks:
  app_internal: