[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
autostart=true

[program:backend]
command=/usr/bin/nodejs /var/www/project/backend/server.js
directory=/var/www/project/
autorestart=true
autostart=true
startretries=0
user=www-data
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend_err.log